// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnbz5IKzwt__URSthaBlPpyc18k5yhL3U',
    appId: '1:1050112750514:web:254998641f94a7b1362aab',
    messagingSenderId: '1050112750514',
    projectId: 'kasuwa-65f25',
    authDomain: 'kasuwa-65f25.firebaseapp.com',
    storageBucket: 'kasuwa-65f25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDifLuCeMcB07z83vd9FWK9oqkNxjph_uY',
    appId: '1:1050112750514:android:9eb266b582e1a1d5362aab',
    messagingSenderId: '1050112750514',
    projectId: 'kasuwa-65f25',
    storageBucket: 'kasuwa-65f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2h28e1_TZZUnCI8nynErGW0rFdS4A3M',
    appId: '1:1050112750514:ios:a955e1dd9f22e39f362aab',
    messagingSenderId: '1050112750514',
    projectId: 'kasuwa-65f25',
    storageBucket: 'kasuwa-65f25.appspot.com',
    iosBundleId: 'com.example.kasuwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2h28e1_TZZUnCI8nynErGW0rFdS4A3M',
    appId: '1:1050112750514:ios:a955e1dd9f22e39f362aab',
    messagingSenderId: '1050112750514',
    projectId: 'kasuwa-65f25',
    storageBucket: 'kasuwa-65f25.appspot.com',
    iosBundleId: 'com.example.kasuwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnbz5IKzwt__URSthaBlPpyc18k5yhL3U',
    appId: '1:1050112750514:web:52686147e6814d82362aab',
    messagingSenderId: '1050112750514',
    projectId: 'kasuwa-65f25',
    authDomain: 'kasuwa-65f25.firebaseapp.com',
    storageBucket: 'kasuwa-65f25.appspot.com',
  );
}
